### ISSUE TITLE
Tried to register two views with the same name SkiaDomView

### ISSUE THREAD

**Issue by PROda221** [SamuelScheit/react-native-skia-list#2]
Hey!
I was trying on this library since I heard its a great list renderer, but I am facing this issue. Can you help me in this?

Thanks!

![image](https://github.com/user-attachments/assets/2ea9afeb-e980-467c-96aa-8ad2248cb2ff)
![image](https://github.com/user-attachments/assets/85b11a19-a4a2-43ef-9069-85e9a28f5a9d)

**Comment by samuelscheit** [comment]
On it

**Comment by samuelscheit** [comment]
- updated the example: https://github.com/SamuelScheit/react-native-skia-list/blob/main/example/app/GettingStarted.tsx
- fixed hot reloading
- updated the dependencies and installation instructions: 
the problem with "Tried to register two views with the same name" is that the skia package was installed twice, once in the root node_modules dir and once inside of the skia-list package directory.
to fix this you have to install the peer dependencies manually:
```
yarn add react-native-skia-list@^0.7.2 @shopify/react-native-skia react-native-keyboard-controller react-native-reanimated react-native-gesture-handler
```

I hope this issue is now fixed for you, feel free to reply if it still occurs.
Sorry that it took so long, I can't live from open source yet and I'm working on this package in my free time, 
If you value my work feel free to [sponsor](https://github.com/sponsors/SamuelScheit) me.

**Comment by PROda221** [comment]
Hey Samuel! Appreciate the work man. I'll test this out when I get the time next. Thanks for update 😊

**Comment by stevengoldberg** [comment]
Hi @SamuelScheit, I'm very interested in trying out this library. I get the same "Tried to register two views with the same name" error as soon as I `import { SkiaFlatList } from 'react-native-skia-list'` somewhere. My project already uses Skia and Gesture Handler elsewhere, so they're already installed separately.
